version: '3'

services:
  mysql:
    image: mysql:8.0.28
    container_name: tododeoji-db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env

  redis:
    image: redis
    container_name: tododeoji-redis
    ports:
      - "6322:6322"

  spring-server:
    platform: linux/amd64
    image: huni123/tododeoji
    container_name: tododeoji
    restart: always
    depends_on:
      - redis
      - mysql
    ports:
      - "8080:8080"